### ISSUE TITLE
Add a README file.

### ISSUE THREAD

**Issue by kerk12** [kerk12/HacktoberfestChecker-cli#1]
As the title implies, we need a README file. Needs to include basic usage guidelines.

**Comment by rohitdaryanani** [comment]
I can try doing this.

**Comment by kerk12** [comment]
@rohitdaryanani Go ahead ;).

**Comment by rohitdaryanani** [comment]
Thanks already pr'ed let me know if it okay

**Comment by kerk12** [comment]
Added on https://github.com/kerk12/HacktoberfestChecker-cli/pull/4
