### ISSUE TITLE
Basic exception handling.

### ISSUE THREAD

**Issue by kerk12** [kerk12/HacktoberfestChecker-cli#2]
Basic exception handling needs to be added to various places inside the script. More specifically:

- Import checking (what if the library isn't installed).
- Input checking (empty values, whatever else...).
- Any other exception not handled properly.

**Comment by arcticbarra** [comment]
I'll take this one 👍

**Comment by haycristhine** [comment]
I'll try adding some more

**Comment by kerk12** [comment]
OK, I think this one's ready to be closed. Thanks @arcticbarra, @haycristhine and @lucassouto.
